stages:
  - test
  - deploy

Test:
  image: python:3.8.8
  stage: test
  before_script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --no-input
  when: on_success
  script:
    - coverage run --include="./*/*" --omit="./manage.py" manage.py test
    - coverage report -m
    - coverage xml -i
  artifacts:
    paths:
      - coverage.xml

Deployment:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=ci-cd-proj --api-key=57befd4c-8e03-4c45-af2c-c41edc886cfd
  environment:
    name: main
    url: ci-cd-proj.herokuapp.com
  only:
    - main